image: archlinux
packages:
  - python
  - python-pip
  - python39
sources:
  - https://github.com/wizzk42/python-etcd3
environment:
  TEST_ETCD_VERSION: v3.5.16
tasks:
  - test: |
      cd python-etcd3
      pip install --progress-bar off -U tox
      curl -L https://github.com/coreos/etcd/releases/download/$TEST_ETCD_VERSION/etcd-$TEST_ETCD_VERSION-linux-amd64.tar.gz -o etcd-$TEST_ETCD_VERSION-linux-amd64.tar.gz
      tar xzvf etcd-$TEST_ETCD_VERSION-linux-amd64.tar.gz
      export PATH=$PATH:~/.local/bin:etcd-$TEST_ETCD_VERSION-linux-amd64

      tox
